### ISSUE TITLE
Allow hooking on health state change

### ISSUE THREAD

**Issue by dmarkhas** [AppsFlyer/go-sundheit#22]
It would be nice if the library offered a way to trigger a function when the service's health status changed. This could be used for logging, or for stopping/starting some components, when the services becomes unhealthy/healthy.

**Comment by eranharel** [comment]
Please take a look at the `health.WithCheckListener(listener CheckListener)` function. 
Let me know if does that for you

**Comment by dmarkhas** [comment]
Seems like it would do the trick, thanks.
