### ISSUE TITLE
Soft Failure of Individual Health Checks

### ISSUE THREAD

**Issue by triwats** [AppsFlyer/go-sundheit#23]
This might be a bit of an anti-pattern and a bit of a quirk of our environment rather than something that is widely beneficial. We're currently using this package to provide a health check that is consumed via an ALB within AWS. It works well, but we have a dependancy in there which is degrading (SOLR), not catastrophic. Therefore, I would like the ability to have a healthcheck that doesn't return a 503 if failed, as a soft check. That way, if we are seeing issues, we can still diagnose quickly as we can see the issue from an application's perspective, but we are in a degraded state that is not fully customer impacting.

Right now, a 503 error will cause our instances to restart, causing us to have operational issues for customers instead. A soft failure here would give us the best of both words of visibility but not impacting our state. We would obviously monitor this application via another mechanism.

Is this something I can already achieve? Alternatively, is this something you think makes sense and would be interested in having as part of go-sundheit?

**Comment by eranharel** [comment]
I hear this question in various forms quite often @triwats.
To my understanding, what you want for your service is more than one endpoint for your health state.
In the Kubernetis world, and in similar orchestration tools you can define [Readiness/Liveness/Startup probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) and define the matching endpoints for your service.

This way your readiness defines your ability to serve requests, and the liveness defines whether your service needs a little nag (errr restart), and you don't get a restart when your dependencies become non responsive or degrade.

To implement that you can create two health repositories, and two endpoints, each with the relevant checks, or use go-sundheit just for one of the cases. I normally use go-sundheit just for the readiness, and the liveness checks are usually simpler, and don't require any scheduling and off-line / cached executions, so I just implement a straight forward endpoint.

Makes sense?

**Comment by eranharel** [comment]
...and sorry for the late response. I had a hectic month...

**Comment by triwats** [comment]
Hey, first off no worries on the response time! Hectic times normally nevermind in the middle of a pandemic. I think the usecase here is even more specific to our monolithic legacy infrastructure. We're using this library to return a functional healthcheck from the ELB that looks at other factors such as a shared EFS (NFS) system. We are effectively using this as the readiness and liveness check but outside of a K8S world. Definitely not ideal, but it works to allow us to scale as the application in question (SAP Hybris) was way before microservices were a thing. 

The requirement here is more to allow us to embed a way to diagnose issues for free text search (SOLR) which is interfaced via this monolith. I think this is probably going to be better served by monitoring elsewhere via metrics/logs. Thanks for the response though! I'm hoping we can make some contributions to this in the future.
