### ISSUE TITLE
Replace OpenCensus with a metrics interface

### ISSUE THREAD

**Issue by sagikazarmark** [AppsFlyer/go-sundheit#24]
Now that OpenTelemetry is becoming a thing, adding support for it would be nice.

However, both OpenTelemetry and OpenCensus are quite heavy dependencies and one might not want to pull in both.

I propose adding an interface for recording metrics that's independent from any metrics collection library. It would allow users to use any implementation (one might just want to use the Prometheus client library, go-kit users could use the go-kit metrics abstraction, etc).

go-sundheit could still ship an OpenCensus implementation, but preferably in a separate module, so that its dependencies are not pulled in by default.

I'd be happy to provide a PR that first relocates OpenCensus integration to a separate module behind a Metrics interface, then an OpenTelemetry implementation in a second PR.

WDYT?

**Comment by eranharel** [comment]
I agree this can be beneficial @sagikazarmark.
I'm probing OpenTelemetry every once in a while, as I'm guessing it will become the de-facto standard soon.
It seems like OpenTelemetry metrics are still alfa, and not that documented yet, so I'm holding...

That said, if you provide a PR that won't complicate things too much, and allow integrating other metrics providers relatively easily, it will be great. I do agree it's a good enhancement, despite the possibility of being a breaking change.

**Comment by sagikazarmark** [comment]
I've given some thoughts to this (and actually tried to put together a PR), but I came across some issues and I have a few more ideas to improve metrics support.

This is the interface I initially came up with:

```go
// Metrics records various metrics about check results and health.
type Metrics interface {
	// CheckStatus records the status of an individual check.
	CheckStatus(pass bool) error

	// CheckDuration records the duration of an individual check.
	CheckDuration(duration time.Duration) error

	// Healthy records the overall health.
	Healthy(healthy bool) error
}
```

I realized this is very similar to the check listener interface already present in the library, except it doesn't have a way to receive all health status. So instead adding a metrics interface, I thought we could add an interface like this:

```go
type HealthListener interface {
	OnResultsUpdated(results map[string]Result)
}
```

The listener would be invoked every time there is a new result. (We probably need to copy the results so that a listener cannot modify the map) This would allow us to implement the current metrics logic as two listeners.

In addition to the above two listeners, I'd implement two aggregated type as well:

```go
type CheckListeners []CheckListener

type HealthListeners []HealthListener
```

Regarding the exposed metrics themselves, I have two suggestions:

- I think it's a bit weird that the "all" health metrics is exposed as the same metric as the individual checks. I'd add a separate metric for that.
- Is there a reason why the fact that a check is passing or not is also added as a label to the metrics? I would assume that's what the individual metric is for.

I realized these are huge changes, probably break backwards compatibility, but I think they would improve the library a lot and technically semver allows breaking changes for 0.x versions. What do you think @eranharel ?

**Comment by bivas** [comment]
@sagikazarmark 
Today, the lib reports metrics per `Check` (by passing the check ID to measure object). 
The interface you proposed seems to be missing that possibility , is that intentional?

By adding an option for multiple `CheckListener` it will be possible to add a listener that simply report metrics. This way, if someone needs a different stats measurement system - it's easily replaceable. Something like:

```go
h := New(WithCheckListener(NewOpenCencusReporter()), WithCheckListener(FooReporter{}))
```

These (future) reporters can also implement the 2nd interface you mentioned (`HealthListener`) to report the general health of the service.

So a simple implementation might look like:
```go
type OpenCensusReporter struct {
    stats FooServer
    mCheckDuration stats.Measure
    mCheckStatus stats.Measure
}

func NewOperCensusReporter() CheckListener {
    return OpenCensusReporter{} // omitting the init of vars
}

func (r *OpenCensusReporter) OnCheckStarted(_ string) {}

func (r *OpenCensusReporter) OnCheckCompleted(name string, result Result) {
    thisCheckCtx := createMonitoringCtx(name, result.IsHealthy()) // omitting the impl from example
    stats.Record(thisCheckCtx, r.mCheckDuration.M(float64(result.Duration)/float64(time.Millisecond)))
    stats.Record(thisCheckCtx, r.mCheckStatus.M(status(result.IsHealthy()).asInt64()))
}

func (r *FooReprter) OnResultsUpdated(results map[string]Result) {
    allHealthy := allHealthy(results) // omitting the impl
    allChecksCtx := createMonitoringCtx(ValAllChecks, allHealthy)
    stats.Record(allChecksCtx, r.mCheckStatus.M(status(allHealthy).asInt64()))
}
```

This will clean the current impl and doesn't add any new mechanism to support (We'll impl open census reporter, for backward compatibility and set it as default).

**Comment by sagikazarmark** [comment]
A couple thoughts:

I'd keep the singular check listener in the health service and implement a `type CheckListeners []CheckListener`. That was the health service is unaware of multiple CheckListeners. `WithCheckListener` could support multiple listeners though:

```go
func WithCheckListener(listeners ...CheckListener)

// ...

h := New(WithCheckListener(NewOpenCencusReporter(), FooReporter{}))
```

> We'll impl open census reporter, for backward compatibility and set it as default

The current master already includes some breaking changes, so even if open census is implemented in this library, I'd keep it in a separate module to avoid the unnecessary dependency and wouldn't import it in the primary module. This will require users to always manually configure it, but that doesn't feel like a huge price to pay in exchange for a possible future migration to OpenTelemetry and avoiding an extremely heavy dependency in the main library.

**Comment by bivas** [comment]
> I'd keep the singular check listener in the health service and implement a type CheckListeners []CheckListener. That was the health service is unaware of multiple CheckListeners

Agree.

> even if open census is implemented in this library, I'd keep it in a separate module to avoid the unnecessary dependency

As there is only a single implementation at the moment, I would extract it to a different module when the time is right. Once we'll add support for _OpenTelemetry_ - we can extract to these reporters to sub-modules.

**Comment by sagikazarmark** [comment]
> As there is only a single implementation at the moment, I would extract it to a different module when the time is right.

One of the primary arguments to extract it is the heavy dependency. For example, I'm going to implement an Open Telemetry reporter myself and use it in my applications. OpenCensus is a heavy dependency that I'd like to avoid. One project I'd like to use it in is Dex: https://github.com/dexidp/dex

**Comment by sagikazarmark** [comment]
I guess this is superseded by #32
