### ISSUE TITLE
API improvements

### ISSUE THREAD

**Issue by sagikazarmark** [AppsFlyer/go-sundheit#26]
A couple ideas to improve the API of the package:

`RegisterCheck` should accept a check and a config separately: `RegisterCheck(check Check, cfg *Config) error`

This would allow making the config optional (given the health checker accepts a default config applied to all checks). I realize this might not make sense in all cases, but it would give the user a cleaner API when they get to learn the package.

I could even imagine

```go
RegisterCheck(check Check) error
RegisterCheckWithConfig(check Check, cfg Config) error
```

Or with functional options:
```go
type CheckOption interface {
    applyCheck(check *check)
}

RegisterCheck(check Check, ...CheckOption) error
```

(Note: #25 implements functional options, this would work on top of that)

---

Consider dropping deregistration: is it really a useful feature? Making the health checker mutable this way is confusing and prone to error in my opinion. Obviously, if there is a legitimate use case it should stay.

As a consequence, I'd also add a `Start` (and `Stop`?) method to the health checker and make `RegisterCheck` return an error for a started health checker.

Alternatively, create a separate `HealthBuilder` that's mutable and build a HealthChecker with the builder that's immutable.

---

I realize these are huge changes, but in the long run these could improve the package API by making it more obvious and compact.

**Comment by eranharel** [comment]
TBH, I don't remember why I added the deregister check API in the first place, but it could be useful for those who want a check that only runs once for example.

I agree the mutability is error prone, but I'm not sure about the usage patterns.

Re check + config on registration, I think this can be a good change. Shouldn't be too hard, though this is breaking.

Start/Stop: IDK... I think most or all use cases only require it to always run

**Comment by sagikazarmark** [comment]
I've sent a PR with the suggested changes.

**Comment by sagikazarmark** [comment]
Done. See the above linked PR (and the PRs linked to that PR).
