### ISSUE TITLE
Add a ping checker

### ISSUE THREAD

**Issue by sagikazarmark** [AppsFlyer/go-sundheit#3]
Similar to [this](https://github.com/InVisionApp/go-health/blob/master/checkers/sql.go#L14), but not necessarily tied to SQL.

**Comment by eranharel** [comment]
@sagikazarmark can you elaborate?
Do you mean something like open a connection to a host, and fail on error?
Add an option to send payload, and expect a response?
Support UDP?

**Comment by sagikazarmark** [comment]
Here is a simple interface that (among others) the sql package implements:

```
type Pinger interface {
	PingContext(ctx context.Context) error
}
```

I'm suggesting to add a checker to this package, which accepts an instance of that interface, so that people don't have to implement a custom one. It has no external dependencies, so it's not a heavy implementation.

**Comment by eranharel** [comment]
@sagikazarmark want to take a look?
https://github.com/AppsFlyer/go-sundheit/pull/6

**Comment by sagikazarmark** [comment]
Sure!
