### ISSUE TITLE
Refactor tests to use jonboulle/clockwork

### ISSUE THREAD

**Issue by sagikazarmark** [AppsFlyer/go-sundheit#34]
While working on the API improvements I found a few Sleeps in the code that caused flaky test runs for me.

I'd suggest adding https://github.com/jonboulle/clockwork to the mix.

**Comment by sagikazarmark** [comment]
@eranharel I've started to look at this one as well.

A couple questions came up:
- How do you feel about adding `github.com/jonboulle/clockwork` as a dependency in the first place? It's a lightweight dependency.
- Initially, I wanted to make the clock an unexported setting that's only overridden in tests. Because other packages also use the main health instance, it doesn't seem to be possible. How do you feel about a public API for setting the clock (falling back to the system clock of course)?
- While playing with tests, I noticed that the main package tests only rely on the checks package to use the `CustomCheck` struct. How do you feel about moving the `CustomCheck` struct to the main package? It doesn't have any dependencies and it's the simplest implementation used widely by several packages. This would also remove the circular dependency between the main package and checks.

While this might seem to be a lot of effort for a small benefit, I actually think that it would improve the correctness and reliability of this library a lot, so I suggest making this change.

**Comment by eranharel** [comment]
* I started playing with that clockwork option. I need to get a feel of what it will be like. 
* I added an option for setting the clock. Noticed our WithDefaults() option is broken... it's not hard to add this though
* OK, I think this makes sense

**Comment by eranharel** [comment]
I take my words back @sagikazarmark 
I think the clockwork lib is problematic for our use case. The problems I see are:

1. You have to carefully replace all usages of the `time` package in production code, else you may get unexpected results, which make it bug prone.
2. We still have to wait for check completion even though we control the time, so either `Sleep()` or a sync mechanism is needed.

So I wrote a little `CheckListener` that looks like so:
```golang
type checkWaiter struct {
	completedChan chan string
}

func newCheckWaiter() *checkWaiter {
	return &checkWaiter{
		completedChan: make(chan string),
	}
}

func (c *checkWaiter) OnCheckRegistered(_ string, _ Result) {}

func (c *checkWaiter) OnCheckStarted(_ string) {}

func (c *checkWaiter) OnCheckCompleted(name string, _ Result) {
	c.completedChan <- name
}

func (c *checkWaiter) awaitChecksCompletion(checkNames ...string) error {
	if len(checkNames) == 0 {
		return nil
	}

	awaitingCompletion := make(map[string]int, len(checkNames))
	for _, c := range checkNames {
		_, ok := awaitingCompletion[c]
		if ok {
			awaitingCompletion[c]++
		} else {
			awaitingCompletion[c] = 1
		}
	}

	for chkName := range c.completedChan {
		fmt.Printf("check '%s' completed\n", chkName)
		remainingCount, ok := awaitingCompletion[chkName]
		if !ok {
			return errors.New(fmt.Sprintf("unexpected check completed: %s", chkName))
		}
		if remainingCount == 1 {
			delete(awaitingCompletion, chkName)
		} else {
			awaitingCompletion[chkName]--
		}

		if len(awaitingCompletion) == 0 {
			break
		}
	}

	return nil
}
```

This allows me to remove the sleeps in the health_test code, and replace with

**Comment by eranharel** [comment]
Example: https://github.com/AppsFlyer/go-sundheit/blob/tests-stabilization/health_test.go#L57

**Comment by eranharel** [comment]
Do you think we still need this ticket @sagikazarmark?

**Comment by sagikazarmark** [comment]
I can live without it 🙂
